blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/afondiel/computer-science-notebook/discussions
    about: Ask questions, share ideas, or start a conversation with the community.
